default_icon: "â¡"
event_organizers_icon:
  "^Upstream$": "ğŸ¢"
  "colleague2@chmouel.com": "ğŸ˜ˆ"
  "boss@chmouel.com": "ğŸ¤ "
title_match_icon:
  "^.*kid pickup.*": "ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦"
  "^[Project to the Moon].*": "ğŸŒ•ï¸"
max_results: 10
skip_non_accepted: true
skip_non_confirmed: false
skip_all_day: true
starts_today_only: false
my_emails:
  - email@email.com
# The time to query Gnome Online Accounts not to refresh calendars
refresh_interval: 60
restrict_to_calendar:
  - Work
title_max_char: 20
calendar_day_prefix_url: "https://calendar.google.com/calendar/r/day/"

# Five minutes before a meeting we will be changing the icon to reflect
# something is coming up.
change_icon_minutes: 5

# We can automatically open the web browser to the meetig url with the
# auto_open_minutes variable. Give it the number of minutes before the meeting
# or 0 to disable. (the auto opening only happen once per meeting).
auto_open_minutes: 0

# You can customize the icons to a svg or png files with those variables :
# icon_default_path: the default icon, it will use the icon
#                    "x-office-calendar-symbolic" from gnome theme by default.
# icon_in_event_path: the icon when in event, it will show a colored calendar
#                     icon by default.
# icon_before_event_path: an icon just before an event to show something is
# coming up.
