default_icon: "â¡"
event_organizers_icon:
  "^Upstream$": "ğŸ¢"
  "colleague2@chmouel.com": "ğŸ˜ˆ"
  "boss@chmouel.com": "ğŸ¤ "
title_match_icon:
  "^.*kid pickup.*": "ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦"
  "^[Project to the Moon].*": "ğŸŒ•ï¸"
max_results: 10
skip_non_accepted: true
my_emails:
  - email@email.com
# The time to query Gnome Online Accounts not to refresh calendars
refresh_interval: 300
restrict_to_calendar:
  - Work
title_max_char: 20
calendar_day_prefix_url: "https://calendar.google.com/calendar/r/day/"
